import type { RouteRecordRaw } from 'vue-router';

const routes: RouteRecordRaw[] = [
  {
    meta: {
      icon: 'lucide:megaphone',
      order: 50,
      title: '运营管理',
    },
    name: 'OperateManager',
    path: '/operate/manager',
    redirect: '/operate/manager/gold-balance',
    children: [
      {
        name: 'AgentActivity',
        path: 'agentActivity',
        component: () => import('#/views/operate/agent-activity.vue'),
        meta: { title: '代理活动' },
      },
      {
        name: 'GoldBalance',
        path: 'gold-balance',
        component: () => import('#/views/operate/gold-balance.vue'),
        meta: { title: '金币余额' },
      },
      {
        name: 'AutoSalaryPayRecord',
        path: '/auto-salary-pay-record',
        component: () => import('#/views/operate/auto-salary-pay-record.vue'),
        meta: { title: '自动发放工资凭据' },
      },
      {
        name: 'UserBankWithdrawMoneyApply',
        path: '/withdraw-money-apply-page',
        component: () =>
          import('#/views/operate/user-bank-withdraw-money-apply.vue'),
        meta: { title: '用户银行卡提现现金申请' },
      },
      {
        name: 'UserBankWithdrawDiamondApply',
        path: '/withdraw-diamond-apply-page',
        component: () =>
          import('#/views/operate/user-bank-withdraw-diamond-apply.vue'),
        meta: { title: '用户银行卡提现钻石申请' },
      },
      {
        name: 'UserBankWithdrawGoldApply',
        path: '/user-bank-withdraw-gold-apply',
        component: () =>
          import('#/views/operate/user-bank-withdraw-gold-apply.vue'),
        meta: { title: '用户银行金币兑换申请' },
      },
      {
        name: 'UserBankDiamondWithdrawGoldApply',
        path: '/user-bank-diamond-withdraw-gold-apply',
        component: () =>
          import('#/views/operate/user-bank-diamond-withdraw-gold-apply.vue'),
        meta: { title: '用户银行卡钻石兑换金币申请' },
      },
      {
        name: 'UserBankBalance',
        path: '/user-bank-balance',
        component: () => import('#/views/operate/user-bank-balance.vue'),
        meta: { title: '用户银行账户' },
      },
      {
        name: 'UserBankRunningWater',
        path: '/user-running-water',
        component: () => import('#/views/operate/user-bank-running-water.vue'),
        meta: { title: '用户银行流水' },
      },
      {
        name: 'CustomerService',
        path: '/customer-service',
        component: () => import('#/views/operate/customer-service.vue'),
        meta: { title: '客服列表' },
      },
      {
        name: 'OperateCp',
        path: 'cp',
        component: () => import('#/views/operate/cp-apply.vue'),
        meta: { title: 'CP申请' },
      },
      {
        name: 'GamePK',
        path: '/game/pk',
        component: () => import('#/views/operate/game-pk.vue'),
        meta: { title: 'PK记录' },
      },
      {
        name: 'InviteUserLog',
        path: 'invite-user-log',
        component: () => import('#/views/operate/invite-user-log.vue'),
        meta: { title: '邀请用户日志' },
      },
      {
        name: 'OperateActivityConfig',
        path: 'activity/cnf',
        component: () => import('#/views/operate/activity-config.vue'),
        meta: { title: '活动配置' },
      },
      {
        name: 'OperateActivityTemplate',
        path: 'activity/template',
        component: () => import('#/views/operate/activity-template.vue'),
        meta: { title: '活动模版' },
      },
      {
        name: 'SysUserFriendshipCard',
        path: '/sys/friendship-card',
        component: () => import('#/views/operate/friendship-card.vue'),
        meta: { title: '用户友谊卡配置' },
      },
      {
        name: 'LotfunInviteUserRule',
        path: '/sys/invite-user-rule',
        component: () => import('#/views/operate/invite-user-rule.vue'),
        meta: { title: '邀请用户配置' },
      },
      {
        name: 'AswatUserAdvertising',
        path: '/sys/user-advertising',
        component: () => import('#/views/operate/user-advertising.vue'),
        meta: { title: '用户观看广告配置' },
      },
      {
        name: 'GameLudo',
        path: '/game-ludo',
        component: () => import('#/views/operate/ludo-game.vue'),
        meta: { title: 'Ludo飞行棋' },
      },
      {
        name: 'SetTop',
        path: 'set-top-room',
        component: () => import('#/views/operate/set-top-room.vue'),
        meta: { title: '置顶房间' },
      },
      {
        name: 'SetHot',
        path: 'set-hot-room',
        component: () => import('#/views/operate/set-hot-room.vue'),
        meta: { title: '热门房间' },
      },
      {
        name: 'RefundDeductTagLog',
        path: 'refund-deduct-tag-log',
        component: () => import('#/views/operate/refund-deduct-tag-log.vue'),
        meta: { title: '退款扣除目标' },
      },
      {
        name: 'PayCountry',
        path: 'pay/country',
        component: () => import('#/views/operate/pay-country.vue'),
        meta: { title: '开通支付国家' },
      },
      {
        name: 'RegionRelation',
        path: 'region/relation',
        component: () => import('#/views/operate/region-relation.vue'),
        meta: { title: '支付区域关系' },
      },
      {
        name: 'PayApplication',
        path: 'pay/application',
        component: () => import('#/views/operate/pay-application.vue'),
        meta: { title: '应用管理' },
      },
      {
        name: 'PayFactory',
        path: 'pay/factory',
        component: () => import('#/views/operate/pay-factory.vue'),
        meta: { title: '支付厂商' },
      },
      {
        name: 'PayChannel',
        path: 'pay/channel',
        component: () => import('#/views/operate/pay-channel.vue'),
        meta: { title: '支付渠道' },
      },
      {
        name: 'OpenPayCountry',
        path: 'open_pay/country',
        component: () => import('#/views/operate/pay-country.vue'),
        meta: { title: '开通支付国家' },
      },
      {
        name: 'OperateCnfLottery',
        path: 'cnf/lottery',
        component: () => import('#/views/operate/lottery-wheel-config.vue'),
        meta: { title: '抽奖品配置' },
      },
      {
        name: 'OperateUserFreight',
        path: 'user_freight',
        component: () => import('#/views/operate/user-freight.vue'),
        meta: { title: '货运代理' },
      },
      {
        name: 'OperateBusinessDevelopment',
        path: 'room/business-development',
        component: () => import('#/views/operate/business-development.vue'),
        meta: { title: 'BD列表' },
      },
      {
        name: 'InviteRewardRecord',
        path: 'user/invite-reward',
        component: () => import('#/views/operate/invite-reward.vue'),
        meta: { title: '邀请用户奖励记录' },
      },
      {
        name: 'OperateImAccountManager',
        path: 'im/account/manager',
        component: () => import('#/views/operate/im-account-manager.vue'),
        meta: { title: 'IM账号管理' },
      },
      {
        name: 'CheckInLog',
        path: 'check/in/log',
        component: () => import('#/views/operate/check-in-log.vue'),
        meta: { title: '用户签到' },
      },
      {
        name: 'OperateUserManage',
        path: 'user',
        component: () => import('#/views/operate/user-manage.vue'),
        meta: { title: '用户列表' },
      },
      {
        name: 'OperateAdministrator',
        path: 'administrator',
        component: () => import('#/views/operate/app-administrator.vue'),
        meta: { title: 'APP管理员' },
      },
      {
        name: 'OperateUserDevice',
        path: 'user/user-device',
        component: () => import('#/views/operate/user-device-list.vue'),
        meta: { title: '用户最新设备列表' },
      },
      {
        name: 'OperateCompensate',
        path: 'compensate',
        component: () => import('#/views/operate/compensate-order.vue'),
        meta: { title: '订单补偿' },
      },
      {
        name: 'OperateToolsOther',
        path: 'tools/other',
        component: () => import('#/views/operate/tools-other.vue'),
        meta: { title: '小工具' },
      },
      {
        name: 'OperateAbnormalLog',
        path: 'abnormal/log',
        component: () => import('#/views/operate/order-abnormal.vue'),
        meta: { title: '异常订单' },
      },
      {
        name: 'OperateUserFreightInfoList',
        path: 'user_freight_info_list',
        component: () => import('#/views/operate/user-freight-info-list.vue'),
        meta: { title: '货运代理流水' },
      },
      {
        name: 'OperateQualityUsersList',
        path: 'quality_users_list',
        component: () => import('#/views/operate/quality-users-list.vue'),
        meta: { title: '高产用户列表' },
      },
      {
        name: 'OperateGoldRunningWater',
        path: 'running/water',
        component: () => import('#/views/operate/gold-running-water.vue'),
        meta: { title: '金币收支记录' },
      },
      {
        name: 'OperateInsideOperationGold',
        path: 'inside-operation-gold',
        component: () => import('#/views/operate/inside-operation-gold.vue'),
        meta: { title: '内部操作金币' },
      },
      {
        name: 'GameCouponRunningWater',
        path: '/game/coupon/running/water',
        component: () => import('#/views/operate/game-coupon-running-water.vue'),
        meta: { title: '游戏券收支记录' },
      },
      {
        name: 'OperateIntegralStream',
        path: 'integral/stream',
        component: () => import('#/views/operate/integral-stream.vue'),
        meta: { title: '积分收支记录' },
      },
      {
        name: 'OperateOrderDetails',
        path: 'order/details',
        component: () => import('#/views/operate/order-details.vue'),
        meta: { title: '订单详情' },
      },
      {
        name: 'OperateReimburse',
        path: 'reimburse',
        component: () => import('#/views/operate/reimburse-order.vue'),
        meta: { title: '退款记录' },
      },
      {
        name: 'OperateGiftConfig',
        path: 'gift',
        component: () => import('#/views/operate/gift-config.vue'),
        meta: { title: '礼物管理' },
      },
      {
        name: 'OperateGameLotteryConfig',
        path: '/game/lottery-config',
        component: () => import('#/views/operate/game-lottery-config.vue'),
        meta: { title: '抽奖概率配置' },
      },
      {
        name: 'OperateBadgeConfig',
        path: 'badge',
        component: () => import('#/views/operate/badge-config.vue'),
        meta: { title: '徽章配置管理' },
      },
      {
        name: 'OperateGiftHistory',
        path: 'gift/history',
        component: () => import('#/views/operate/gift-history.vue'),
        meta: { title: '礼物赠送记录' },
      },
      {
        name: 'GameRedPacketRecord',
        path: '/game/red/packet/record',
        component: () => import('#/views/operate/game-red-packet-record.vue'),
        meta: { title: '红包发送列表' },
      },
      {
        name: 'LuckyGiftRuleConfig',
        path: '/game/lucky-gift/rule-config/config',
        component: () => import('#/views/operate/lucky-gift-rule-config.vue'),
        meta: { title: '幸运礼物规则配置' },
      },
      {
        name: 'LuckyGiftGiveRecord',
        path: '/game/lucky-gift/give-record',
        component: () => import('#/views/operate/lucky-gift-give-record.vue'),
        meta: { title: '幸运礼物送礼记录' },
      },
      {
        name: 'LuckyGiftStandardConfig',
        path: '/game/lucky-gift/standard-config/config',
        component: () => import('#/views/operate/lucky-gift-standard-config.vue'),
        meta: { title: '幸运礼物规格配置' },
      },
      {
        name: 'GameLuckyBox',
        path: '/game/lucky-box',
        component: () => import('#/views/operate/lucky-box.vue'),
        meta: { title: 'LuckyBox抽奖记录' },
      },
      {
        name: 'GameFruitDaysLog',
        path: '/game/fruit/log/fruit-days-log',
        component: () => import('#/views/operate/fruit-days-log.vue'),
        meta: { title: '摩天轮游戏每日数据' },
      },
      {
        name: 'OperateFruitTaskConfig',
        path: 'game/fruit/task-config',
        component: () => import('#/views/operate/fruit-task-config.vue'),
        meta: { title: '摩天轮任务配置' },
      },
      {
        name: 'GameTeenPatti',
        path: '/game/teen-patti',
        component: () => import('#/views/operate/teen-patti.vue'),
        meta: { title: '炸金花' },
      },
      {
        name: 'OperateContributionBalance',
        path: 'contribution/balance',
        component: () => import('#/views/operate/contribution-balance.vue'),
        meta: { title: '房间贡献余额' },
      },
      {
        name: 'OperatePush',
        path: 'push',
        component: () => import('#/views/operate/push.vue'),
        meta: { title: '消息推送' },
      },
      {
        name: 'OperateOnlineRoom',
        path: 'online/room',
        component: () => import('#/views/operate/online-room.vue'),
        meta: { title: '在线房间' },
      },
      {
        name: 'OperateRoomProfile',
        path: 'profile/room',
        component: () => import('#/views/operate/room-profile.vue'),
        meta: { title: '房间资料信息' },
      },
      {
        name: 'OperateSysCountry',
        path: 'sys/country',
        component: () => import('#/views/operate/system-country.vue'),
        meta: { title: '国家管理' },
      },
      {
        name: 'OperateSysBanner',
        path: 'sys/banner',
        component: () => import('#/views/operate/system-banner.vue'),
        meta: { title: '系统banner管理' },
      },
      {
        name: 'OperateStartPage',
        path: 'sys/start/page',
        component: () => import('#/views/operate/start-page-config.vue'),
        meta: { title: 'App启动页' },
      },
      {
        name: 'OperateNoticeMessage',
        path: 'notice/message',
        component: () => import('#/views/operate/notice-message.vue'),
        meta: { title: '系统公告管理' },
      },
      {
        name: 'OperateMikeType',
        path: 'mike/type',
        component: () => import('#/views/operate/mike-type-config.vue'),
        meta: { title: '麦位类型管理' },
      },
      {
        name: 'OperateGameConfig',
        path: 'game-config',
        component: () => import('#/views/operate/game-config.vue'),
        meta: { title: '游戏列表' },
      },
      {
        name: 'OperateMikeTypeList',
        path: 'mike/type/list',
        component: () => import('#/views/operate/mike-type-list.vue'),
        meta: { title: '购买麦位类型流水' },
      },
      {
        name: 'RunningWaterUserProps',
        path: '/running/water/user/props',
        component: () => import('#/views/operate/user-props-running-water.vue'),
        meta: { title: '用户道具流水' },
      },
      {
        name: 'UserDiamondBalance',
        path: '/user/diamond-balance',
        component: () => import('#/views/operate/user-diamond-balance.vue'),
        meta: { title: '用户钻石余额列表' },
      },
      {
        name: 'UserDiamondRunWater',
        path: '/user/diamond-run-water',
        component: () =>
          import('#/views/operate/user-diamond-running-water.vue'),
        meta: { title: '用户钻石流水列表' },
      },
      {
        name: 'UserActivityReceive',
        path: '/user/user-activity-receive',
        component: () => import('#/views/operate/user-activity-receive.vue'),
        meta: { title: '用户活动领奖记录' },
      },
      {
        name: 'GameTrumpet',
        path: '/game/trumpet',
        component: () => import('#/views/operate/trumpet-list.vue'),
        meta: { title: '喇叭列表' },
      },
      {
        name: 'OperateGameEgg',
        path: '/game/egg',
        component: () => import('#/views/operate/game-egg.vue'),
        meta: { title: '砸金蛋' },
      },
      {
        name: 'BeautifulNumberApply',
        path: '/user/beautiful-number-apply',
        component: () => import('#/views/operate/beautiful-number-apply.vue'),
        meta: { title: '用户申请靓号记录' },
      },
      {
        name: 'OperateBeautifulNumber',
        path: 'beautiful-number',
        component: () => import('#/views/operate/beautiful-number.vue'),
        meta: { title: '靓号池管理' },
      },
      {
        name: 'ActivityRoomContribution',
        path: '/activity/room/contribution',
        component: () => import('#/views/operate/room-contribution.vue'),
        meta: { title: '房间支持活动' },
      },
      {
        name: 'ActivityHallFame',
        path: '/activity/hall-fame',
        component: () => import('#/views/operate/hall-fame.vue'),
        meta: { title: '自定义名人堂' },
      },
    ],
  },
];

export default routes;
